"""POST /api/solver/repair - Mode A mass repair from docs/solver.md.
Runs the CP-SAT solver (app/analysis/repair_solver.py) over a chosen set
of findings and, if it found any moves, lands them in a normal change
set - the same review/validate/approve/export pipeline every other edit
in this app goes through. Nothing here writes to the timetable directly;
"solving" and "applying" are as separate as "suggesting" and "applying"
already are for suggest_fixes()."""

import sqlite3

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from app.analysis.repair_solver import REPAIR_ELIGIBLE_RULES, solve_repair
from app.api.deps import get_db_writable
from app.audit import log_event
from app.changes.service import add_proposed_change, create_change_set, validate_change_set

router = APIRouter()


class RepairRequest(BaseModel):
    # None (or omitted) means "every open, repair-eligible finding" - the
    # honest default for a "fix everything you can" button, rather than
    # silently including rule types that would just come back as
    # not_eligible and clutter the result.
    finding_ids: list[int] | None = None
    time_budget_seconds: float | None = None
    created_by: str


def _finding_titles(conn: sqlite3.Connection, finding_ids: list[int]) -> dict[int, str]:
    if not finding_ids:
        return {}
    placeholders = ",".join("?" for _ in finding_ids)
    return {
        r["id"]: r["title"]
        for r in conn.execute(f"SELECT id, title FROM finding WHERE id IN ({placeholders})", tuple(finding_ids))
    }


@router.post("/solver/repair")
def repair(request: RepairRequest, conn: sqlite3.Connection = Depends(get_db_writable)) -> dict:
    finding_ids = request.finding_ids
    if finding_ids is None:
        placeholders = ",".join("?" for _ in REPAIR_ELIGIBLE_RULES)
        finding_ids = [
            r["id"] for r in conn.execute(
                f"SELECT id FROM finding WHERE status = 'OPEN' AND rule_id IN ({placeholders})",
                tuple(REPAIR_ELIGIBLE_RULES),
            )
        ]

    if not finding_ids:
        return {
            "status": "NO_MOVABLE_ENTRIES", "change_set_id": None,
            "moved_count": 0, "movable_entry_count": 0, "solve_time_seconds": 0.0,
            "findings_resolved": [], "findings_unresolved": [], "not_eligible": [],
        }

    result = solve_repair(conn, finding_ids, request.time_budget_seconds or 20.0)

    change_set_id = None
    if result.moves:
        change_set_id = create_change_set(
            conn,
            f"Mass repair ({len(result.moves)} move{'s' if len(result.moves) != 1 else ''})",
            f"Generated by the CP-SAT repair solver - see docs/mass-repair.md. "
            f"Resolved {len(result.findings_resolved)} of {len(result.findings_resolved) + len(result.findings_unresolved)} "
            f"requested finding(s) with {len(result.moves)} move(s).",
            request.created_by,
        )
        room_by_code = {r["code"]: r["id"] for r in conn.execute("SELECT id, code FROM room")}
        period_lookup = {
            (r["day_code"], r["code"]): r["id"]
            for r in conn.execute("SELECT p.id, p.code, d.code AS day_code FROM period p JOIN day d ON d.id = p.day_id")
        }
        day_by_code = {r["code"]: r["id"] for r in conn.execute("SELECT id, code FROM day")}

        # A move isn't traced back to which specific input finding(s) it
        # resolves (repair candidates can share entries across several
        # findings at once, unlike a single suggest_fixes() candidate) -
        # every proposed_change in this set is linked to every finding the
        # run resolved, which is honest at the change-set level even
        # though it's coarser than suggest_fixes()'s per-candidate linking.
        for move in result.moves:
            after_day_id = day_by_code.get(move.after["day_code"])
            after_period_id = period_lookup.get((move.after["day_code"], move.after["period_code"]))
            after_room_id = room_by_code.get(move.after["room_code"]) if move.after["room_code"] else None
            add_proposed_change(
                conn, change_set_id, move.entry_id,
                after_day_id=after_day_id, after_period_id=after_period_id, after_room_id=after_room_id,
                reason="Proposed by the mass repair solver",
                finding_ids=result.findings_resolved,
            )
        validate_change_set(conn, change_set_id)
        log_event(
            conn, "mass_repair_run", f"Mass repair produced {len(result.moves)} move(s) in change set {change_set_id}",
            actor=request.created_by, entity_type="change_set", entity_id=change_set_id,
            detail={
                "status": result.status, "finding_ids": finding_ids,
                "findings_resolved": result.findings_resolved, "findings_unresolved": result.findings_unresolved,
                "moved_count": result.moved_count, "movable_entry_count": result.movable_entry_count,
                "solve_time_seconds": result.solve_time_seconds,
            },
        )

    titles = _finding_titles(conn, finding_ids)
    return {
        "status": result.status,
        "change_set_id": change_set_id,
        "moved_count": result.moved_count,
        "movable_entry_count": result.movable_entry_count,
        "solve_time_seconds": result.solve_time_seconds,
        "findings_resolved": [{"id": fid, "title": titles.get(fid)} for fid in result.findings_resolved],
        "findings_unresolved": [{"id": fid, "title": titles.get(fid)} for fid in result.findings_unresolved],
        "not_eligible": [
            {"finding_id": ne.finding_id, "rule_id": ne.rule_id, "reason": ne.reason} for ne in result.not_eligible
        ],
    }
